insert into Warehouse (warehouse_name) values ('Andriette');
insert into Warehouse (warehouse_name) values ('Melisenda');
insert into Warehouse (warehouse_name) values ('Roi');
insert into Warehouse (warehouse_name) values ('Peyton');
insert into Warehouse (warehouse_name) values ('Myra');

insert into Stock (warehouse_id, stock_name, quantity) values (2, 'Garden', 20);
insert into Stock (warehouse_id, stock_name, quantity) values (4, 'Computers', 26);
insert into Stock (warehouse_id, stock_name, quantity) values (4, 'Sports', 23);
insert into Stock (warehouse_id, stock_name, quantity) values (4, 'Automotive', 21);
insert into Stock (warehouse_id, stock_name, quantity) values (1, 'Music', 18);
insert into Stock (warehouse_id, stock_name, quantity) values (5, 'Beauty', 50);
insert into Stock (warehouse_id, stock_name, quantity) values (5, 'Jewelry', 88);
insert into Stock (warehouse_id, stock_name, quantity) values (3, 'Toys', 78);
insert into Stock (warehouse_id, stock_name, quantity) values (1, 'Books', 42);
insert into Stock (warehouse_id, stock_name, quantity) values (4, 'Games', 48);
insert into Stock (warehouse_id, stock_name, quantity) values (1, 'Garden', 24);
insert into Stock (warehouse_id, stock_name, quantity) values (2, 'Tools', 74);
insert into Stock (warehouse_id, stock_name, quantity) values (2, 'Garden', 20);
insert into Stock (warehouse_id, stock_name, quantity) values (2, 'Garden', 4);
insert into Stock (warehouse_id, stock_name, quantity) values (2, 'Baby', 82);
insert into Stock (warehouse_id, stock_name, quantity) values (4, 'Movies', 76);
insert into Stock (warehouse_id, stock_name, quantity) values (5, 'Kids', 96);
insert into Stock (warehouse_id, stock_name, quantity) values (4, 'Baby', 78);
insert into Stock (warehouse_id, stock_name, quantity) values (3, 'Music', 50);
insert into Stock (warehouse_id, stock_name, quantity) values (4, 'Jewelry', 80);